#!/bin/bash
# amt clean - remove all amt related files

msg "remove .amt working directory"
rm -rf $AMT_WORKING_DIRECTORY/.amt  > $AMT_STDOUT 2>&1

msg "remove application.* files"
rm -rf $AMT_WORKING_DIRECTORY/application.*  > $AMT_STDOUT 2>&1
